apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pplale-cms-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://github.com/ieyoukan/home-manifests.git
    targetRevision: main
    path: apps/pplale-cms
  destination:
    server: https://kubernetes.default.svc
    namespace: pplale-cms
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 5
