apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: videoplayer
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: backend=ghcr.io/ieyoukan/video-player-backend
    argocd-image-updater.argoproj.io/backend.update-strategy: newest-build
    argocd-image-updater.argoproj.io/backend.allow-tags: regexp:^v[0-9]
    argocd-image-updater.argoproj.io/write-back-method: argocd
    argocd-image-updater.argoproj.io/backend.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/backend.helm.image-tag: image.tag
spec:
  project: default
  source:
    repoURL: https://github.com/ieyoukan/ubichill-videoplayer.git
    targetRevision: main
    path: charts/video-player-backend
    helm:
      releaseName: video-player-backend
      valuesObject:
        image:
          repository: ghcr.io/ieyoukan/video-player-backend
          tag: 0.1.4
          pullPolicy: IfNotPresent
        ingress:
          enabled: true
          className: cloudflare
          annotations: {}
          hosts:
            - host: videoplayer.youkan.uk
              paths:
                - path: /
                  pathType: Prefix
  destination:
    server: https://kubernetes.default.svc
    namespace: video-player-backend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
