apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: videoplayer
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ieyoukan/ubichill-videoplayer.git
    targetRevision: main
    path: charts/video-player-backend
    helm:
      releaseName: video-player-backend
      valuesObject:
        image:
          repository: ghcr.io/ieyoukan/video-player-backend
          tag: latest
          pullPolicy: Always
        ingress:
          enabled: true
          className: cloudflare
          annotations: {}
          hosts:
            - host: videoplayer.youkan.uk
              paths:
                - path: /
                  pathType: Prefix
  destination:
    server: https://kubernetes.default.svc
    namespace: video-player-backend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
