apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mediamtx-secrets
  namespace: mediamtx
spec:
  encryptedData:
    publisher-pass: AgAHM49VSqcgH0nesOdJxvpVLg3nO5eqAAQH8/2P1SB9X+9tJBozzGvYPSxdc5GPlzLyXkMnz6tmMMtdIyvXagjuC9TlDQ6NeG33FGovq+K7yOEmRudHJoMScY35snZDscriFoDWBr9xTumOtMOdXkEyEa9J1nWJ6x6fXEMshyygR0ltpvsuBo5YOeaLky40IQW93e8wQPfs0dCrhHZycUzPkM/1vj2a2sll9jxZ6u4cPHS0GLRnQj0fpfEA9M9fwHrz0YXDzm5SyHH44VbpQlRFNVG6FQ0yQ4/H19uZ0y+t/HDgR1YTXFMUJIDmLG6KBWOrDjkgH1hHqmXlMriFjqRA9k0NlFg9h8gdEOax/DlqzleLzzK6N1lixPNfOzi/JiU9HddlCQPPREabpux44OUrqlb+1j9jG1yqOIxYfxvx/psjyG6BoGnmSPVJ1YxWx5JWb8crgTbmUDeT43GNvEqaEKFSW1frwAFVnkOfOTHNy9qM9BAVWU+MFa8jpXqWOL2SvLQhUY7R/FyjGaei1VFcdtKCeflALE3ZOxPzxCHjOmTRq/n64fdtjY81t8y+EJb2hBpI+E2uvm2SiRzg0l1KBAYJmFkK34tQyUTLVtcb1dxlkPaJrHuhsrGBI2kVycxDD8z8Ue/78cJVDqX2t+TyAjzz1jW3ZV6QTGGowfMGevxWhL6x/0PbNTusqUxEz3uP6q4RFjS33P87pCExSlkH0U98vQ894jUvXAkP901FGr41RenchaBCQReS
    publisher-user: AgDXai2NwXYJ7oGeKUmv+2qTcvjb/my7EBFBmC2vl4AHg+Jv2lB/W/1VrYcQp0F5V+5ju376dba7QZz3FbIOliazIcdNszNrhbYk3p5X6yrMVb0Rqu7BWAWiXRqLuUAEgBlwiTzKEEZoc00t47SpE7BMW07hoW31QcYkGAfWDJano4CWBDO/08NSqKrWpwu3w/3gyeMbccsFvwkleqyRGNdN14nw8sXUCw9sOFZ+uYidrkdu3MPIZijkUH7/DhchGsEDpr10YjXsv5DsEs42lk+73tp9M+uj9dozb85/OD0e5BJkq0zIuA8mQ0fa02eFpxE2RiFey1ny2L4370vKGMJvOzX4IXQPXo8lD2/Fv0wO/lSH/xh7MCLF5utfIImaHs2+0nIkNdHANDxwPOm3VNVP4ZU+phISfShM7BIYSjPI/dj1o24bvR7SiAcPqA6jHXpThJWnhrg4w8mra4b6KYXsH8tejepDQRCldOQDLBXXIJpDrSWQfoowo/+uQViDtBlM4QvxNEcPWR3TPf0ighE7GRvh5aq9jxB6p8aH/zYcTTB7TLMcYG8n1d94pcygdLzo1MupEzQ69qfkyj3umTltZ7BbNp5AF4rO1OFninuibzZNdnystUiaxLCEjoL6LfmoRV4OjzTeV2uLqiH8dKMiljkzJU3t0kRIImXR8VGjYbvArh+2RVS0hivVUU/RU9QRxruL911uYSs=
  template:
    metadata:
      creationTimestamp: null
      name: mediamtx-secrets
      namespace: mediamtx
---
